In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("StudentPerformanceFactors.csv")
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   object
 3   Access_to_Resources         6607 non-null   object
 4   Extracurricular_Activities  6607 non-null   object
 5   Sleep_Hours                 6607 non-null   int64
 6   Previous_Scores             6607 non-null   int64
 7   Motivation_Level            6607 non-null   object
 8   Internet_Access             6607 non-null   object
 9   Tutoring_Sessions           6607 non-null   int64
 10  Family_Income               6607 non-null   object
 11  Teacher_Quality             6529 non-null   object
 12  School_Type                 6607 non-null   object
 13  Peer_Influence              6607 non-null   object
 14  Physical_Activity           6607 non-null   int64
 15  Learning_Disabilities       6607 non-null   object
 16  Parental_Education_Level    6517 non-null   object
 17  Distance_from_Home          6540 non-null   object
 18  Gender                      6607 non-null   object
 19  Exam_Score                  6607 non-null   int64
dtypes: int64(7), object(13)
memory usage: 1.0+ MB

In [4]:
df.isnull().sum()

Hours_Studied                  0
Attendance                     0
Parental_Involvement           0
Access_to_Resources            0
Extracurricular_Activities     0
Sleep_Hours                    0
Previous_Scores                0
Motivation_Level               0
Internet_Access                0
Tutoring_Sessions              0
Family_Income                  0
Teacher_Quality               78
School_Type                    0
Peer_Influence                 0
Physical_Activity              0
Learning_Disabilities          0
Parental_Education_Level      90
Distance_from_Home            67
Gender                         0
Exam_Score                     0
dtype: int64

In [5]:
for col in ['Teacher_Quality', 
            'Parental_Education_Level', 
            'Distance_from_Home']:
    df[col].fillna(df[col].mode()[0], inplace=True)

C:\Users\Anmol.24\AppData\Local\Temp\ipykernel_8588\3630819504.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

In [6]:
from sklearn.preprocessing import OrdinalEncoder

In [7]:
ordinal_cols = [
    "Parental_Involvement",
    "Access_to_Resources",
    "Motivation_Level",
    "Family_Income",
    "Teacher_Quality",
    "Parental_Education_Level",
    "Peer_Influence"
]

categories = [
    ["Low", "Medium", "High"],
    ["Low", "Medium", "High"],
    ["Low", "Medium", "High"],
    ["Low", "Medium", "High"],
    ["Low", "Medium", "High"],
    ["High School", "College", "Postgraduate"],
    ["Positive","Neutral","Negative"]
]

In [8]:
oe = OrdinalEncoder(categories=categories)

df[ordinal_cols] = oe.fit_transform(df[ordinal_cols])

In [9]:
df[ordinal_cols].head()

,Parental_Involvement,Access_to_Resources,Motivation_Level,Family_Income,Teacher_Quality,Parental_Education_Level,Peer_Influence
0,0.0,2.0,0.0,0.0,1.0,0.0,0.0
1,0.0,1.0,0.0,1.0,1.0,1.0,2.0
2,1.0,1.0,1.0,1.0,1.0,2.0,1.0
3,0.0,1.0,1.0,1.0,1.0,0.0,2.0
4,1.0,1.0,1.0,1.0,2.0,1.0,1.0

In [10]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()


df["Internet_Access"] = le.fit_transform(df["Internet_Access"])
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,0.0,2.0,No,7,73,0.0,1,0,0.0,1.0,Public,0.0,3,No,0.0,Near,Male,67
1,19,64,0.0,1.0,No,8,59,0.0,1,2,1.0,1.0,Public,2.0,4,No,1.0,Moderate,Female,61
2,24,98,1.0,1.0,Yes,7,91,1.0,1,2,1.0,1.0,Public,1.0,4,No,2.0,Near,Male,74
3,29,89,0.0,1.0,Yes,8,98,1.0,1,1,1.0,1.0,Public,2.0,4,No,0.0,Moderate,Male,71
4,19,92,1.0,1.0,Yes,6,65,1.0,1,3,1.0,2.0,Public,1.0,4,No,1.0,Near,Female,70

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   float64
 3   Access_to_Resources         6607 non-null   float64
 4   Extracurricular_Activities  6607 non-null   object
 5   Sleep_Hours                 6607 non-null   int64
 6   Previous_Scores             6607 non-null   int64
 7   Motivation_Level            6607 non-null   float64
 8   Internet_Access             6607 non-null   int64
 9   Tutoring_Sessions           6607 non-null   int64
 10  Family_Income               6607 non-null   float64
 11  Teacher_Quality             6607 non-null   float64
 12  School_Type                 6607 non-null   object
 13  Peer_Influence              6607 non-null   float64
 14  Physical_Activity           6607 non-null   int64
 15  Learning_Disabilities       6607 non-null   object
 16  Parental_Education_Level    6607 non-null   float64
 17  Distance_from_Home          6607 non-null   object
 18  Gender                      6607 non-null   object
 19  Exam_Score                  6607 non-null   int64
dtypes: float64(7), int64(8), object(5)
memory usage: 1.0+ MB

In [12]:
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,0.0,2.0,No,7,73,0.0,1,0,0.0,1.0,Public,0.0,3,No,0.0,Near,Male,67
1,19,64,0.0,1.0,No,8,59,0.0,1,2,1.0,1.0,Public,2.0,4,No,1.0,Moderate,Female,61
2,24,98,1.0,1.0,Yes,7,91,1.0,1,2,1.0,1.0,Public,1.0,4,No,2.0,Near,Male,74
3,29,89,0.0,1.0,Yes,8,98,1.0,1,1,1.0,1.0,Public,2.0,4,No,0.0,Moderate,Male,71
4,19,92,1.0,1.0,Yes,6,65,1.0,1,3,1.0,2.0,Public,1.0,4,No,1.0,Near,Female,70

In [13]:
X = df.drop(columns=[
    "Exam_Score",
    "Gender",
    "Distance_from_Home",
    "School_Type",
    "Extracurricular_Activities",
    "Physical_Activity",
    "Learning_Disabilities"
])

y = df["Exam_Score"]

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)

In [15]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(4955, 13)
(1652, 13)
(4955,)
(1652,)

In [16]:
print(X_train.dtypes)

Hours_Studied                 int64
Attendance                    int64
Parental_Involvement        float64
Access_to_Resources         float64
Sleep_Hours                   int64
Previous_Scores               int64
Motivation_Level            float64
Internet_Access               int64
Tutoring_Sessions             int64
Family_Income               float64
Teacher_Quality             float64
Peer_Influence              float64
Parental_Education_Level    float64
dtype: object

In [17]:
from sklearn.tree import DecisionTreeRegressor

dt_unpruned = DecisionTreeRegressor(random_state=42)
dt_unpruned.fit(X_train, y_train)

DecisionTreeRegressor(random_state=42)

In [18]:
y_train_pred = dt_unpruned.predict(X_train)
y_test_pred = dt_unpruned.predict(X_test)

In [19]:
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

print("Unpruned Train R2:", r2_score(y_train, y_train_pred))
print("Unpruned Test R2 :", r2_score(y_test, y_test_pred))

print("Unpruned Train MAE:", mean_absolute_error(y_train, y_train_pred))
print("Unpruned Test MAE :", mean_absolute_error(y_test, y_test_pred))

print("Unpruned Train RMSE:", np.sqrt(mean_squared_error(y_train, y_train_pred)))
print("Unpruned Test RMSE :", np.sqrt(mean_squared_error(y_test, y_test_pred)))

Unpruned Train R2: 1.0
Unpruned Test R2 : 0.033867838631778335
Unpruned Train MAE: 0.0
Unpruned Test MAE : 1.7960048426150121
Unpruned Train RMSE: 0.0
Unpruned Test RMSE : 3.627561297693397

In [20]:
from sklearn.tree import DecisionTreeRegressor

dt_pruned = DecisionTreeRegressor(
    max_depth=12,
    min_samples_split=10,
    min_samples_leaf=5,
    random_state=42
)
dt_pruned.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=12, min_samples_leaf=5, min_samples_split=10,
                      random_state=42)

In [21]:
y_train_pred = dt_pruned.predict(X_train)
y_test_pred = dt_pruned.predict(X_test)

In [22]:
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

print("Pruned Train R2:", r2_score(y_train, y_train_pred))
print("Pruned Test R2 :", r2_score(y_test, y_test_pred))

print("Pruned Train MAE:", mean_absolute_error(y_train, y_train_pred))
print("Pruned Test MAE :", mean_absolute_error(y_test, y_test_pred))

print("Pruned Train RMSE:", np.sqrt(mean_squared_error(y_train, y_train_pred)))
print("Pruned Test RMSE :", np.sqrt(mean_squared_error(y_test, y_test_pred)))

Pruned Train R2: 0.7530923912293778
Pruned Test R2 : 0.5134650687383775
Pruned Train MAE: 1.0176386699159168
Pruned Test MAE : 1.5832264227292134
Pruned Train RMSE: 1.9648348481744289
Pruned Test RMSE : 2.5742664889023192

In [23]:
import joblib


joblib.dump(dt_pruned, "decision_tree_model.pkl")

joblib.dump(oe, "ordinal_encoder.pkl")


print("ML pipeline saved successfully!")

ML pipeline saved successfully!